title: "Prabaljit Walia"
email: prabaljitwalia4546@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "/prabal4546.github.io" 
form_url: "https://formspree.io/f/mnqlbokq"
twitter_username: PrabaljitW
github_username:  prabal4546

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg

# your google analytics tag goes here
# how to get your analytics tag?
# https://support.google.com/analytics/answer/1008080
google-analytics: XX-000000000-0
